# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WmsLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_url', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('minx', models.FloatField()),
                ('maxx', models.FloatField()),
                ('miny', models.FloatField()),
                ('maxy', models.FloatField()),
                ('boundary_geo', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
