# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmslayer',
            name='base_url',
            field=models.URLField(max_length=255),
        ),
    ]
