# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 14:05
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0003_geoserverraster'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverraster',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
