# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0004_geoserverraster_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=b'datafile_uploads')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.IntegerField(choices=[(0, 'shapefile'), (1, 'csv')])),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='geoserverraster',
            name='file',
            field=models.FileField(upload_to=b'raster_uploads'),
        ),
    ]
