# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0005_auto_20170526_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file_type',
            field=models.CharField(choices=[('shp', 'ShapeFile'), ('csv', 'Comma separated values(csv)')], max_length=5),
        ),
    ]
