# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import visor.models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0006_auto_20170526_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='geoserverraster',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to=b'datafile_uploads', validators=[visor.models.validate_datafile_extension]),
        ),
        migrations.AlterField(
            model_name='geoserverraster',
            name='file',
            field=models.FileField(upload_to=b'raster_uploads', validators=[visor.models.validate_tif_extension]),
        ),
    ]
