# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0008_auto_20170530_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geoserverraster',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasters', to=settings.AUTH_USER_MODEL),
        ),
    ]
