# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0009_auto_20170530_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverraster',
            name='srs_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
