# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0010_geoserverraster_srs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverraster',
            name='geoserver_layername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geoserverraster',
            name='geoserver_workspace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
