# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visor', '0012_auto_20170704_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateTimeField(auto_now_add=True)),
                ('file_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visor.DataFile')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('raster_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visor.GeoServerRaster')),
            ],
        ),
    ]
