# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0014_operation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='execution_log',
            field=models.TextField(blank=True),
        ),
    ]
