# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0016_auto_20170710_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(db_column='srid', primary_key=True, serialize=False)),
                ('auth_name', models.TextField(db_column='auth_name')),
                ('auth_srid', models.DecimalField(db_column='auth_srid', decimal_places=0, max_digits=10)),
                ('srtext', models.TextField(db_column='srtext')),
                ('proj4text', models.TextField(db_column='proj4text')),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
    ]
