# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0017_spatialrefsys'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='srs',
            field=models.ForeignKey(default=4326, on_delete=django.db.models.deletion.CASCADE, related_name='data_files_by_srs', to='visor.SpatialRefSys'),
            preserve_default=False,
        ),
    ]
