# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 10:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0018_datafile_srs'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverraster',
            name='raster',
            field=django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326),
        ),
    ]
