# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 14:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0019_geoserverraster_raster'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='points_geo',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_type',
            field=models.CharField(choices=[('shp', 'ShapeFile'), ('csv', 'Comma separated values(csv)')], default='csv', max_length=5),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='srs',
            field=models.ForeignKey(default=4326, on_delete=django.db.models.deletion.CASCADE, related_name='data_files_by_srs', to='visor.SpatialRefSys'),
        ),
    ]
