# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0021_auto_20170906_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
