# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0022_auto_20170907_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='result',
        ),
        migrations.AddField(
            model_name='operation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='result_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
