# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('visor', '0023_auto_20170907_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='execution_log',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='finished',
        ),
        migrations.AddField(
            model_name='operation',
            name='taskmeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.TaskMeta'),
        ),
    ]
