# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0024_auto_20170908_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='taskmeta',
        ),
        migrations.AddField(
            model_name='operation',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
