# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('visor', '0025_auto_20170908_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='task_id',
        ),
        migrations.AddField(
            model_name='operation',
            name='task_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.TaskMeta'),
        ),
    ]
