# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0027_auto_20170908_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='geoserverraster',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rasters_in_list', to='visor.RasterList'),
        ),
    ]
