# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0029_auto_20170920_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoserverraster',
            name='list',
        ),
        migrations.AddField(
            model_name='rasterlist',
            name='rasters',
            field=models.ManyToManyField(to='visor.GeoServerRaster'),
        ),
    ]
